// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeYB4ea_cldndEBn_1i2dx1JX5JLS7Nyw',
    appId: '1:438935519077:web:4743218030f5d9289fab8c',
    messagingSenderId: '438935519077',
    projectId: 'soundaudiodb-c32f6',
    authDomain: 'soundaudiodb-c32f6.firebaseapp.com',
    storageBucket: 'soundaudiodb-c32f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTB2cFJ6Ew6Sk3qCxWlO-dud8BcdlRF4',
    appId: '1:438935519077:android:f5cf6e46a969d7a99fab8c',
    messagingSenderId: '438935519077',
    projectId: 'soundaudiodb-c32f6',
    storageBucket: 'soundaudiodb-c32f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq6P5hEDXUukEySkN9JPYrjAw4Xairlk0',
    appId: '1:438935519077:ios:80474ff3eff19be19fab8c',
    messagingSenderId: '438935519077',
    projectId: 'soundaudiodb-c32f6',
    storageBucket: 'soundaudiodb-c32f6.firebasestorage.app',
    iosBundleId: 'com.example.mobileSoundaudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq6P5hEDXUukEySkN9JPYrjAw4Xairlk0',
    appId: '1:438935519077:ios:80474ff3eff19be19fab8c',
    messagingSenderId: '438935519077',
    projectId: 'soundaudiodb-c32f6',
    storageBucket: 'soundaudiodb-c32f6.firebasestorage.app',
    iosBundleId: 'com.example.mobileSoundaudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeYB4ea_cldndEBn_1i2dx1JX5JLS7Nyw',
    appId: '1:438935519077:web:0b35a262e9d0d4589fab8c',
    messagingSenderId: '438935519077',
    projectId: 'soundaudiodb-c32f6',
    authDomain: 'soundaudiodb-c32f6.firebaseapp.com',
    storageBucket: 'soundaudiodb-c32f6.firebasestorage.app',
  );
}
